directories:
  output: dist-electron
  buildResources: build
appId: com.electron.login
productName: Electron Login
files:
  - filter:
      - dist/**/*
      - electron/**/*
mac:
  category: public.app-category.utilities
win:
  target: nsis
electronVersion: 29.4.6
